name: Deploy-Application
run-name: Deployment initiated by ${{ github.actor }}
on:
  workflow_dispatch:
jobs:
    deploy-frontend-application:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Pulling code from required branch
              uses: actions/checkout@v4
              with:
                ref: main

            - name: copy file via ssh key
              uses: appleboy/scp-action@v0.1.7
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                source: "dist/*"
                target: sale-tool/
            
            - name: Configure SSH
              run: sudo echo "CASignatureAlgorithms +ssh-rsa" > /etc/ssh/sshd_config
            
            - name: Run remote command via SSH
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USER }}
                key: ${{ secrets.KEY }}
                script: |
                    sudo rm -rvf /usr/share/nginx/sales-tool/*
                    sudo cp -rvf sale-tool/dist/* /usr/share/nginx/sales-tool/
                    sudo rm -rvf sale-tool/*
                    sudo systemctl restart nginx.service